import { Poppins } from "next/font/google";
import "./globals.css";
import Providers from "@/components/share/provider";
import { Toaster } from "sonner";
import LayoutWrapper from "@/components/LayoutWrapper";



const poppins = Poppins({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-poppins",
});

export const metadata = {
  title: "ThePigeonHub",
  description: "Generated by ThePigeonHub",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en"  >
      <body
       suppressHydrationWarning  className={`${poppins.variable}  antialiased `}
      >
        <Providers>
         <LayoutWrapper>
         <div>
            <div className="">
              <Toaster richColors position="top-center" />
              <main>{children}</main>
            </div>
          </div>
         </LayoutWrapper>
        </Providers>
      </body>
    </html>
  );
}
